name: pipeline

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: [ self-hosted, linux ]
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login GHCR
        run: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u guilhermelinosp --password-stdin > /dev/null 2>&1

      - name: Generate version
        id: version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION="${{ github.ref_name }}"
          else
            VERSION="v1.0.${{ github.run_number }}"
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest \
                       -t ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }} \
                       . --quiet

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest > /dev/null 2>&1
          docker push ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }} > /dev/null 2>&1

  release:
    needs: build
    runs-on: [ self-hosted, linux ]
    if: github.ref_type != 'tag'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]" > /dev/null 2>&1
          git config user.email "github-actions[bot]@users.noreply.github.com" > /dev/null 2>&1

      - name: Create version tag
        run: |
          git tag -a "${{ needs.build.outputs.version }}" -m "Release ${{ needs.build.outputs.version }}" > /dev/null 2>&1
          git push origin "${{ needs.build.outputs.version }}" > /dev/null 2>&1 || true
